[artf7222] Improve probability of all tests passing
Test failure on solaris-x86:

junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: there should be 1 running job according to the service expected:<1> but was:<2>
				      at com.collabnet.svnedge.admin.JobsInfoServiceTests$_testJobsRunningAndFinished_closure4.doCall(JobsInfoServiceTests.groovy:63)

* test/unit/com/collabnet/svnedge/admin/JobsInfoServiceTests.groovy
  lengthen job run times (and corresponding sleep times) to help avoid spurious errors
  due to slow running test boxes.



git-svn-id: https://ctf.open.collab.net/svn/repos/svnedge/trunk@3292 03e8f217-bfc6-4b7c-bcb7-0738c91e2c5f